module.exports = {
    ADDRESS_LINE_1: 28,
    ADDRESS_LINE_2: 29,
    CONTACT_NUMBER: 27,
    LANDMARK: 30,
    PINCODE: 31,
    SKU_ARRAY: 17,
    FIXED_SKU_QUANTITY: 6,
    FIXED_SKU_UNIT_PRICE: 13,
    FIXED_SKU_CODE: 1,
    OBJECT_ATTR_ID: 11,
    FIXED_SKU: 50,
    OBJECT_SAROJ_FAREYE: 'ObjectSarojFareye',
    TOTAL_AMOUNT: 'TotalAmount',
    ARRAY_SAROJ_FAREYE:'ArraySarojFareye'
}