module.exports = {
    ADDRESS_LINE_1: 28,
    ADDRESS_LINE_2: 29,
    CONTACT_NUMBER: 27,
    LANDMARK: 30,
    PINCODE: 31,
    SKU_ARRAY: 17,
    SKU_ORIGINAL_QUANTITY:15,
    SKU_CODE:51,
    SKU_ACTUAL_QUANTITY:16,
    TOTAL_ORIGINAL_QUANTITY:35,
    TOTAL_ACTUAL_QUANTITY:36,
    SKU_ACTUAL_AMOUNT:32,
    SKU_UNIT_PRICE:14
}