# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Fareye' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Fareye
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
  pod 'Firebase/Messaging'

  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

  target 'FareyeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Fareye-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Fareye-tvOS

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
      target.build_configurations.each do |config|
          config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
      end
  end
end
