
const userSummary =  {
  "id":"/userSummary",
  "type":"object",
  "properties": {
    "activeTimeInMillis": {"type": " integer"},
    "appVersion": {"type": "string"},
    "avgSpeed": {"type": "number"},
    "cashCollected": {"type": "number"},
    "cashCollectedByCard": {"type": "number"},
    "cashPayment": {"type": "number"},
    "cityId": {"type": " integer"},
    "companyId": {"type": " integer" },
    "cugCallIncomingCount": {"type": " integer" },
    "cugCallIncomingDuration": {"type": " integer" },
    "cugCallOutgoingCount": {"type": " integer" },
    "cugCallOutgoingDuration": {"type": " integer" },
    "date": {"type": "string"},
    "failCount": {"type": " integer" },
    "firstLat": {"type": "number" },
    "firstLong": {"type": "number" },
    "gpsKms": {"type": "number" },
    "haltDuration": {"type": "number" },
    "hubId": {"type": " integer" },
    "id" : {"type": " integer"},
    "imeiNumber": {"type": "string" },
    "lastBattery": {"type": " integer" },
    "lastCashCollected": {"type": "number" },
    "lastLat": {"type": "number" },
    "lastLng": {"type": "number" },
    "lastLocationDatetime": {"type": "string" },
    "lastLogoutTime": {"type": "string" },
    "lastOrderNumber": {"type": "string" },
    "lastOrderTime": {"type": "string" },
    "lastSpeed": {"type": "number" },
    "maxSpeed": {"type": "number" },
    "odometerKms": {"type": "number" },
    "officialCallIncomingCount": {"type": " integer" },
    "officialCallIncomingDuration": {"type": " integer" },
    "officialCallOutgoingCount": {"type": " integer" },
    "officialCallOutgoingDuration": {"type": " integer" },
    "officialSmsSentCount": {"type": " integer" },
    "pendingCount": {"type": " integer" },
    "personalCallIncomingCount": {"type": " integer" },
    "personalCallIncomingDuration": {"type": " integer" },
    "personalCallOutgoingCount": {"type": " integer" },
    "personalCallOutgoingDuration": {"type": " integer" },
    "personalSmsSentCount": {"type": " integer" },
    "successCount": {"type": " integer" },
    "travelDuration": {"type": "number" },
    "userId": {"type": " integer"},
  }
};

module.exports = userSummary;
