
const userSummary = {
  "id": "/userSummary",
  "type": "object",
  "properties": {
    "activeTimeInMillis": { "type": ["number", null], "required": true },
    "avgSpeed": { "type": "number", "required": true },
    "cashCollected": { "type": "number", "required": true },
    "cashCollectedByCard": { "type": "number", "required": true },
    "cashPayment": { "type": "number", "required": true },
    "cityId": { "type": "number", "required": true },
    "companyId": { "type": "number", "required": true },
    "cugCallIncomingCount": { "type": "number", "required": true },
    "cugCallIncomingDuration": { "type": "number", "required": true },
    "cugCallOutgoingCount": { "type": "number", "required": true },
    "cugCallOutgoingDuration": { "type": "number", "required": true },
    "date": { "type": "string", "required": true },
    "failCount": { "type": "number", "required": true },
    "firstLat": { "type": ["number", null], "required": true },
    "firstLong": { "type": ["number", null], "required": true },
    "gpsKms": { "type": ["number", null], "required": true },
    "haltDuration": { "type": "number", "required": true },
    "hubId": { "type": "number", "required": true },
    "id": { "type": "number", "required": true },
    "imeiNumber": { "type": ["string", null], "required": true },
    "lastBattery": { "type": ["number", null], "required": true },
    "lastCashCollected": { "type": ["number", null], "required": true },
    "lastLat": { "type": ["number", null], "required": true },
    "lastLng": { "type": ["number", null], "required": true },
    "lastLocationDatetime": { "type": "string", "required": true },
    "lastLogoutTime": { "type": ["string", null], "required": true },
    "lastOrderNumber": { "type": ["string", null], "required": true },
    "lastOrderTime": { "type": ["string", null], "required": true },
    "lastSpeed": { "type": ["number", null], "required": true },
    "maxSpeed": { "type": "number", "required": true },
    "odometerKms": { "type": "number", "required": true },
    "officialCallIncomingCount": { "type": "number", "required": true },
    "officialCallIncomingDuration": { "type": "number", "required": true },
    "officialCallOutgoingCount": { "type": "number", "required": true },
    "officialCallOutgoingDuration": { "type": "number", "required": true },
    "officialSmsSentCount": { "type": "number", "required": true },
    "pendingCount": { "type": "number", "required": true },
    "personalCallIncomingCount": { "type": "number", "required": true },
    "personalCallIncomingDuration": { "type": "number", "required": true },
    "personalCallOutgoingCount": { "type": "number", "required": true },
    "personalCallOutgoingDuration": { "type": "number", "required": true },
    "personalSmsSentCount": { "type": "number", "required": true },
    "successCount": { "type": "number", "required": true },
    "travelDuration": { "type": "number", "required": true },
    "userId": { "type": "number", "required": true },
    "nextJobTransactionId": { "type": [null, "number"], "required": true },
    "appVersion": { "type": ["string", null], "required": true },
  }
};

module.exports = userSummary;
